stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

test:
  stage: test
  image: node:22
  before_script:
    - npm ci
  script:
    - npm run lint

build:
  stage: build
  image: node:22
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  stage: deploy
  image: docker:27
  services:
    - docker:27-dind
  before_script:
    - docker info
    - apk add --no-cache openssl-client sshpass
  script:
    - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdn
    - docker build --build-arg VITE_APP_API_URL=$VITE_APP_API_URL:3001/api -t $DOCKER_USERNAME/$CI_PROJECT_NAME:latest .
    - docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:latest
    - |
      sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_IP
      echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdn &&
      docker pull $DOCKER_USERNAME/$CI_PROJECT_NAME:latest &&
      docker stop frontend-app || true &&
      docker rm -f frontend-app || true &&
      docker run -d --name frontend-app -p 3000:3000 $DOCKER_USERNAME/$CI_PROJECT_NAME:latest